jurusan = [
    "Pendidikan Dokter", 
    "Pendidikan Dokter Gigi",
    "Matematika",
    "Biologi",
    "Geografi",
    "Fisika",
    "Kimia",
    "Statistika",
    "Ilmu Aktuaria",
    "Geofisika",
    "Geologi",
    "Teknik Sipil",
    "Teknik Mesin",
    "Teknik Elektro",
    "Teknik Metalurgi dan Material",
    "Arsitektur",
    "Teknik Kimia",
    "Teknik Industri",
    "Teknik Lingkungan",
    "Teknik Perkapalan",
    "Teknik Komputer",
    "Arsitektur Interior",
    "Teknologi Bioproses",
    "Teknik Biomedik",
    "Ilmu Hukum",
    "Ilmu Ekonomi",
    "Manajemen",
    "Akuntansi",
    "Ilmu Ekonomi Islam",
    "Bisnis Islam",
    "Arkeologi",
    "Ilmu Filsafat",
    "Ilmu Sejarah",
    "Ilmu Perpustakaan",
    "Sastra Arab",
    "Sastra Indonesia",
    "Sastra Daerah untuk Sastra Jawa",
    "Sastra Cina",
    "Sastra Jepang",
    "Sastra Inggris",
    "Sastra Perancis",
    "Sastra Jerman",
    "Sastra Rusia",
    "Sastra Belanda",
    "Bahasa dan Kebudayaan Korea",
    "Psikologi",
    "Ilmu Politik",
    "Sosiologi",
    "Kriminologi",
    "Ilmu Kesejahteraan Sosial",
    "Ilmu Hubungan Internasional",
    "Ilmu Komunikasi",
    "Antropologi Sosial",
    "Kesehatan Masyarakat",
    "Gizi",
    "Keselamatan dan Kesehatan Kerja",
    "Kesehatan Lingkungan",
    "Ilmu Komputer",
    "Sistem Informasi",
    "Ilmu Keperawatan",
    "Farmasi",
    "Ilmu Administrasi Fiskal",
    "Ilmu Administrasi Negara",
    "Ilmu Administrasi Niaga"
]